spring:
  profiles:
    active: core, db
  messages:
    encoding: UTF-8

  cjdropship:
    api:
      auth:
        cj-email: "bimeni89@gmail.com"
        cj-apiKey: "8696a1e060b64e1ab99e3f16cac7a87a"
        access-url: "https://developers.cjdropshipping.com/api2.0/v1/authentication/getAccessToken"
        refresh-url: "https://developers.cjdropshipping.com/api2.0/v1/authentication/refreshAccessToken"
      category:
        category-list-_url: "https://developers.cjdropshipping.com/api2.0/v1/product/getCategory"
      product:
        list-url: "https://developers.cjdropshipping.com/api2.0/v1/product/list"
        product-detail-url: "https://developers.cjdropshipping.com/api2.0/v1/product"



logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall.core:  DEBUG
    spring:
      devtools:
        restart:
          enabled: false
