litemall:
  # Developers should set it to their own wx related information
  wx:
    app-id: wxa5b486c6b918ecfb
    app-secret: e04004829d4c383b4db7769d88dfbca1
    mch-id: 111111
    mch-key: xxxxxx
    notify-url: http://www.example.com/wx/order/pay-notify
    # Merchant certificate file path
    # Please refer to "Merchant Certificate"
    # 一节 https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3
    key-path: xxxxx
    # Message push configuration token
    token:
    # Message push configuration AesKey
    aes-key:

  # Info for Stripe Payment
  stripe:
    publishedKey: pk_test_7ZlwiqEnPTuI80hU5JPBHnX5
    secretKey: sk_test_3Li1wcFBsz0AeFTSHBOGm5Yb
    webhook-url: https://www.example.com/stripe/webhook/order-paid

  #通知相关配置
  notify:
    mail:
      # Email notification configuration. Mailboxes are generally used to receive business notifications,
      # such as receiving new orders. sendto defines email recipients, usually mall operators.
      enable: false
      host: smtp.exmail.qq.com
      username: ex@ex.com.cn
      password: XXXXXXXXXXXXX
      sendfrom: ex@ex.com.cn
      sendto: ex@qq.com
      port: 465
      # Short message template notification configuration
      # Short messages are used to notify customers, such as shipping SMS notifications.
      # Please pay attention to the configuration format; please refer to the NotifyType enumeration value for template-name and template-templateId.
    sms:
      enable: false
      # If it is Tencent Cloud SMS, set the active value tencent
      # If it is Alibaba Cloud SMS, set the active value aliyun
      active: tencent
      sign: litemall
      template:
      - name: paySucceed
        templateId: 156349
      - name: captcha
        templateId: 156433
      - name: ship
        templateId: 158002
      - name: refund
        templateId: 159447
      tencent:
        appid: 111111111
        appkey: xxxxxxxxxxxxxx
      aliyun:
        regionId: xxx
        accessKeyId: xxx
        accessKeySecret: xxx

  # Kuainiao Logistics Query Configuration
  express:
    enable: false
    appId: "XXXXXXXXX"
    appKey: "XXXXXXXXXXXXXXXXXXXXXXXXX"
    vendors:
    - code: "ZTO"
      name: "中通快递"
    - code: "YTO"
      name: "圆通速递"
    - code: "YD"
      name: "韵达速递"
    - code: "YZPY"
      name: "邮政快递包裹"
    - code: "EMS"
      name: "EMS"
    - code: "DBL"
      name: "德邦快递"
    - code: "FAST"
      name: "快捷快递"
    - code: "ZJS"
      name: "宅急送"
    - code: "TNT"
      name: "TNT快递"
    - code: "UPS"
      name: "UPS"
    - code: "DHL"
      name: "DHL"
    - code: "FEDEX"
      name: "FEDEX联邦(国内件)"
    - code: "FEDEX_GJ"
      name: "FEDEX联邦(国际件)"

  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: local
    # 本地对象存储配置信息
    local:
      storagePath: storage
      # 这个地方应该是wx模块的WxStorageController的fetch方法对应的地址
      address: http://localhost:8080/wx/storage/fetch/
    # 阿里云对象存储配置信息
    aliyun:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      accessKeyId: 111111
      accessKeySecret: xxxxxx
      bucketName: litemall
    # 腾讯对象存储配置信息
    # 请参考 https://cloud.tencent.com/document/product/436/6249
    tencent:
      secretId: AKIDOccMr856uoU1Tsa2MQL5aqseBUWRrb5i
      secretKey: XqtgEhIdrupTs4ygaWlkUUXv3w3FiwuD
      region: ap-shanghai
      bucketName: vytech-1300096589
    # 七牛云对象存储配置信息
    qiniu:
      endpoint: http://pd5cb6ulu.bkt.clouddn.com
      accessKey: 111111
      secretKey: xxxxxx
      bucketName: litemall
  cjdropship:
    api:
      auth:
        cj-email: "bimeni89@gmail.com"
        cj-apiKey: "8696a1e060b64e1ab99e3f16cac7a87a"
        access-url: "https://developers.cjdropshipping.com/api2.0/v1/authentication/getAccessToken"
        refresh-url: "https://developers.cjdropshipping.com/api2.0/v1/authentication/refreshAccessToken"
      category:
        category-list-_url: "https://developers.cjdropshipping.com/api2.0/v1/product/getCategory"
      product:
        list-url: "https://developers.cjdropshipping.com/api2.0/v1/product/list"
        product-detail-url: "https://developers.cjdropshipping.com/api2.0/v1/product"

