version: "3.8"
services:
  litemall-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: litemall
      MYSQL_USER: litemall
      MYSQL_PASSWORD: Calliste_1006
    ports:
      - "3307:3306"
    volumes:
      - litemall-db-data:/var/lib/mysql

    command: --socket=/var/run/mysqld/mysqld.sock

  litemall-core:
      image: litemall/litemall-core:${TAG:-0.1.0}
      depends_on:
        - litemall-db
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://litemall-db:3306/litemall?useSSL=false&serverTimezone=UTC
        SPRING_DATASOURCE_USERNAME: litemall
        SPRING_DATASOURCE_PASSWORD: Calliste_1006
      ports:
        - "8081:8081"


  litemall-wx-api:
      image: litemall/litemall-wx-api:${TAG:-0.1.0}
      depends_on:
        - litemall-db
        - litemall-core
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://litemall-db:3306/litemall?useSSL=false&serverTimezone=UTC
      ports:
        - "8082:8082"

  litemall-admin-api:
      image: litemall/litemall-admin-api:${TAG:-0.1.0}
      depends_on:
        - litemall-db
        - litemall-core
      ports:
        - "8083:8083"

#  litemall-react:
#      image: litemall/litemall-all-react-war:${TAG:-0.1.0}
#      ports:
#        - "80:80"
#      networks:
#        - litemall-network

  litemall-all:
      image: litemall/litemall-all:${TAG:-0.1.0}
      depends_on:
        - litemall-db
        - litemall-core
      ports:
        - "8084:8084"


volumes:
    litemall-db-data:

