package org.linlinjava.litemall.goods.infrastructure.acl.ocs;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.List;
import java.util.Map;

/**
 * Lean projection of the OCS {@code SearchResult} JSON. Only the fields the
 * goods-list DTO mapper consumes are declared; unknown fields are ignored so
 * OCS shape changes don't break us.
 *
 * <p>Shape verified against the live container:
 * {@code {"slices":[{"matchCount":N,"facets":[...],"hits":[{"document":{"id":"...","data":{...}}}]}],
 * "sortOptions":[...],"meta":{...}}}. Facets/sortOptions/meta are generated by OCS for every
 * search with the current index config (term + interval facets, sort options, query relaxation),
 * so they are bound here and surfaced through {@code SearchService}.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class OcsSearchResult {

    private List<Slice> slices;
    private List<SortOption> sortOptions;
    private Map<String, Object> meta;

    public List<Slice> getSlices() {
        return slices;
    }

    public void setSlices(List<Slice> slices) {
        this.slices = slices;
    }

    public List<SortOption> getSortOptions() {
        return sortOptions;
    }

    public void setSortOptions(List<SortOption> sortOptions) {
        this.sortOptions = sortOptions;
    }

    public Map<String, Object> getMeta() {
        return meta;
    }

    public void setMeta(Map<String, Object> meta) {
        this.meta = meta;
    }

    public long totalMatchCount() {
        if (slices == null) {
            return 0L;
        }
        long total = 0L;
        for (Slice s : slices) {
            total += s.getMatchCount();
        }
        return total;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Slice {
        private long matchCount;
        private List<Hit> hits;
        private List<Facet> facets;

        public long getMatchCount() {
            return matchCount;
        }

        public void setMatchCount(long matchCount) {
            this.matchCount = matchCount;
        }

        public List<Hit> getHits() {
            return hits;
        }

        public void setHits(List<Hit> hits) {
            this.hits = hits;
        }

        public List<Facet> getFacets() {
            return facets;
        }

        public void setFacets(List<Facet> facets) {
            this.facets = facets;
        }
    }

    /**
     * A single facet (e.g. {@code brand} term facet, {@code price} interval facet). OCS already
     * excludes a facet's own active filter from its counts, so {@code entries} stay multi-select
     * friendly.
     */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Facet {
        private String fieldName;
        private String type;
        private List<FacetEntry> entries;

        public String getFieldName() {
            return fieldName;
        }

        public void setFieldName(String fieldName) {
            this.fieldName = fieldName;
        }

        public String getType() {
            return type;
        }

        public void setType(String type) {
            this.type = type;
        }

        public List<FacetEntry> getEntries() {
            return entries;
        }

        public void setEntries(List<FacetEntry> entries) {
            this.entries = entries;
        }
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class FacetEntry {
        private String key;
        private String id;
        private long docCount;
        private boolean selected;

        public String getKey() {
            return key;
        }

        public void setKey(String key) {
            this.key = key;
        }

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }

        public long getDocCount() {
            return docCount;
        }

        public void setDocCount(long docCount) {
            this.docCount = docCount;
        }

        public boolean isSelected() {
            return selected;
        }

        public void setSelected(boolean selected) {
            this.selected = selected;
        }
    }

    /**
     * An available sort. {@code field} + {@code sortOrder} (ASC/DESC) are bound; the param value a
     * caller sends back is derived by {@code SearchService} ({@code field} for ASC, {@code -field}
     * for DESC — the syntax verified against the live searcher).
     */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class SortOption {
        private String label;
        private String field;
        private String sortOrder;
        private boolean active;

        public String getLabel() {
            return label;
        }

        public void setLabel(String label) {
            this.label = label;
        }

        public String getField() {
            return field;
        }

        public void setField(String field) {
            this.field = field;
        }

        public String getSortOrder() {
            return sortOrder;
        }

        public void setSortOrder(String sortOrder) {
            this.sortOrder = sortOrder;
        }

        public boolean isActive() {
            return active;
        }

        public void setActive(boolean active) {
            this.active = active;
        }
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Hit {
        private Document document;

        public Document getDocument() {
            return document;
        }

        public void setDocument(Document document) {
            this.document = document;
        }
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Document {
        private String id;
        private Map<String, Object> data;

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }

        public Map<String, Object> getData() {
            return data;
        }

        public void setData(Map<String, Object> data) {
            this.data = data;
        }
    }
}
