package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallCategory;
import org.linlinjava.litemall.db.domain.LitemallCategoryExample;

public interface LitemallCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_category
     *
     * @mbg.generated
     */
    long countByExample(LitemallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_category
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_category
     *
     * @mbg.generated
     */
    int insert(LitemallCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_category
     *
     * @mbg.generated
     */
    int insertSelective(LitemallCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_category
     *
     * @mbg.generated
     */
    LitemallCategory selectOneByExample(LitemallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_category
     *
     * @mbg.generated
     */
    LitemallCategory selectOneByExampleSelective(@Param("example") LitemallCategoryExample example, @Param("selective") LitemallCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_category
     *
     * @mbg.generated
     */
    List<LitemallCategory> selectByExampleSelective(@Param("example") LitemallCategoryExample example, @Param("selective") LitemallCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_category
     *
     * @mbg.generated
     */
    List<LitemallCategory> selectByExample(LitemallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_category
     *
     * @mbg.generated
     */
    LitemallCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_category
     *
     * @mbg.generated
     */
    LitemallCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_category
     *
     * @mbg.generated
     */
    LitemallCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LitemallCategory row, @Param("example") LitemallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LitemallCategory row, @Param("example") LitemallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_category
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_category
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}