package org.linlinjava.litemall.db.dao;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.linlinjava.litemall.db.domain.LitemallUser;
import org.linlinjava.litemall.db.domain.LitemallUserExample;

public interface LitemallUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    long countByExample(LitemallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    int insert(LitemallUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    int insertSelective(LitemallUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    LitemallUser selectOneByExample(LitemallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    LitemallUser selectOneByExampleSelective(@Param("example") LitemallUserExample example, @Param("selective") LitemallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    List<LitemallUser> selectByExampleSelective(@Param("example") LitemallUserExample example, @Param("selective") LitemallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    List<LitemallUser> selectByExample(LitemallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    LitemallUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    LitemallUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    LitemallUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LitemallUser row, @Param("example") LitemallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LitemallUser row, @Param("example") LitemallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);

    @Select("SELECT now_money FROM litemall_user WHERE id = #{userId} AND deleted = 0")
    BigDecimal selectNowMoneyByUserId(@Param("userId") Integer userId);

    @Update("UPDATE litemall_user SET now_money = now_money + #{amount}, update_time = NOW() WHERE id = #{userId} AND deleted = 0")
    int incrementNowMoney(@Param("userId") Integer userId, @Param("amount") BigDecimal amount);

    @Update("UPDATE litemall_user SET now_money = now_money - #{amount}, update_time = NOW() WHERE id = #{userId} AND now_money >= #{amount} AND deleted = 0")
    int decrementNowMoney(@Param("userId") Integer userId, @Param("amount") BigDecimal amount);

    @Select("SELECT integral FROM litemall_user WHERE id = #{userId} AND deleted = 0")
    Integer selectIntegralByUserId(@Param("userId") Integer userId);

    @Update("UPDATE litemall_user SET integral = integral + #{amount}, update_time = NOW() WHERE id = #{userId} AND deleted = 0")
    int incrementIntegral(@Param("userId") Integer userId, @Param("amount") Integer amount);

    @Update("UPDATE litemall_user SET integral = integral - #{amount}, update_time = NOW() WHERE id = #{userId} AND integral >= #{amount} AND deleted = 0")
    int decrementIntegral(@Param("userId") Integer userId, @Param("amount") Integer amount);

    @Select("SELECT experience FROM litemall_user WHERE id = #{userId} AND deleted = 0")
    Integer selectExperienceByUserId(@Param("userId") Integer userId);

    @Update("UPDATE litemall_user SET experience = experience + #{amount}, sign_num = sign_num + #{signDelta}, update_time = NOW() WHERE id = #{userId} AND deleted = 0")
    int incrementExperienceAndSign(@Param("userId") Integer userId, @Param("amount") Integer amount, @Param("signDelta") Integer signDelta);

    @Update("UPDATE litemall_user SET experience = experience + #{amount}, update_time = NOW() WHERE id = #{userId} AND deleted = 0")
    int incrementExperience(@Param("userId") Integer userId, @Param("amount") Integer amount);

    // ------------------------------------------------------------------
    // Wave 5 affiliate — statements live in LitemallUserMapper.xml.
    // credit/debit are the brokerage twins of incrementNowMoney/
    // decrementNowMoney above (guarded UPDATE; debit 0-rows on overdraw).
    // ------------------------------------------------------------------

    int creditBrokerage(@Param("userId") Integer userId, @Param("amount") BigDecimal amount);

    int debitBrokerage(@Param("userId") Integer userId, @Param("amount") BigDecimal amount);

    BigDecimal selectBrokeragePriceByUserId(@Param("userId") Integer userId);

    /** The user's referrer binding (0 = none); null when the user is unknown/deleted. */
    Integer selectSpreadUidByUserId(@Param("userId") Integer userId);

    /** Non-null only for a live (not deleted) user with {@code is_promoter = 1}. */
    LitemallUser selectLivePromoter(@Param("userId") Integer userId);

    /** Page of users referred by {@code spreadUid}, newest binding first. */
    List<LitemallUser> selectTeamBySpreadUid(@Param("spreadUid") Integer spreadUid,
                                             @Param("offset") int offset,
                                             @Param("limit") int limit);

    long countBySpreadUid(@Param("spreadUid") Integer spreadUid);
}