package org.linlinjava.litemall.db.dao;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.linlinjava.litemall.db.domain.LitemallUser;
import org.linlinjava.litemall.db.domain.LitemallUserExample;

public interface LitemallUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    long countByExample(LitemallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    int insert(LitemallUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    int insertSelective(LitemallUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    LitemallUser selectOneByExample(LitemallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    LitemallUser selectOneByExampleSelective(@Param("example") LitemallUserExample example, @Param("selective") LitemallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    List<LitemallUser> selectByExampleSelective(@Param("example") LitemallUserExample example, @Param("selective") LitemallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    List<LitemallUser> selectByExample(LitemallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    LitemallUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    LitemallUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    LitemallUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LitemallUser row, @Param("example") LitemallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LitemallUser row, @Param("example") LitemallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);

    @Select("SELECT now_money FROM litemall_user WHERE id = #{userId} AND deleted = 0")
    BigDecimal selectNowMoneyByUserId(@Param("userId") Integer userId);

    @Update("UPDATE litemall_user SET now_money = now_money + #{amount}, update_time = NOW() WHERE id = #{userId} AND deleted = 0")
    int incrementNowMoney(@Param("userId") Integer userId, @Param("amount") BigDecimal amount);

    @Update("UPDATE litemall_user SET now_money = now_money - #{amount}, update_time = NOW() WHERE id = #{userId} AND now_money >= #{amount} AND deleted = 0")
    int decrementNowMoney(@Param("userId") Integer userId, @Param("amount") BigDecimal amount);

    @Select("SELECT integral FROM litemall_user WHERE id = #{userId} AND deleted = 0")
    Integer selectIntegralByUserId(@Param("userId") Integer userId);

    @Update("UPDATE litemall_user SET integral = integral + #{amount}, update_time = NOW() WHERE id = #{userId} AND deleted = 0")
    int incrementIntegral(@Param("userId") Integer userId, @Param("amount") Integer amount);

    @Update("UPDATE litemall_user SET integral = integral - #{amount}, update_time = NOW() WHERE id = #{userId} AND integral >= #{amount} AND deleted = 0")
    int decrementIntegral(@Param("userId") Integer userId, @Param("amount") Integer amount);

    @Select("SELECT experience FROM litemall_user WHERE id = #{userId} AND deleted = 0")
    Integer selectExperienceByUserId(@Param("userId") Integer userId);

    @Update("UPDATE litemall_user SET experience = experience + #{amount}, sign_num = sign_num + #{signDelta}, update_time = NOW() WHERE id = #{userId} AND deleted = 0")
    int incrementExperienceAndSign(@Param("userId") Integer userId, @Param("amount") Integer amount, @Param("signDelta") Integer signDelta);

    @Update("UPDATE litemall_user SET experience = experience + #{amount}, update_time = NOW() WHERE id = #{userId} AND deleted = 0")
    int incrementExperience(@Param("userId") Integer userId, @Param("amount") Integer amount);

    @Update("UPDATE litemall_user SET spread_uid = #{spreadUid}, spread_time = NOW(), `path` = #{path}, update_time = NOW() WHERE id = #{userId} AND spread_uid = 0 AND deleted = 0")
    int bindSpread(@Param("userId") Integer userId, @Param("spreadUid") Integer spreadUid, @Param("path") String path);

    @Update("UPDATE litemall_user SET spread_count = spread_count + 1, update_time = NOW() WHERE id = #{userId} AND is_promoter = 1 AND deleted = 0")
    int incrementSpreadCount(@Param("userId") Integer userId);
}