package org.linlinjava.litemall.core.infrastructure.acl.client.cjdropshipclient.authentication;


import org.linlinjava.litemall.core.config.CJDropshippingConfig;
import org.linlinjava.litemall.core.infrastructure.acl.dto.cjdropshipdto.authentication.CJAuthenticationResponse;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestTemplate;

@Component
public class CJAuthenticationClient {

    private final RestTemplate restTemplate;
    private final CJDropshippingConfig config;

    public CJAuthenticationClient(RestTemplate restTemplate, CJDropshippingConfig conf) {
        this.restTemplate = restTemplate;
        this.config = conf;
    }

    /**
     *
     * @param email
     * @param password // This password parameter corresponds to the CJAPI key generated by CJDropship
     * @return
     */
    public CJAuthenticationResponse accessToken(String email, String password){
        HttpHeaders headers =  new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);

        String requestBody = String.format("{\"email\": \"%s\", \"password\": \"%s\"}", email, password);
        HttpEntity<String>  request = new HttpEntity<>(requestBody, headers);

        ResponseEntity<CJAuthenticationResponse>  response = restTemplate.postForEntity(
                config.getAccessUrl(), request, CJAuthenticationResponse.class);
        if(response.getStatusCode() == HttpStatus.OK && response.getBody() != null){
            return response.getBody();
        } else {
            throw new RuntimeException("Authentication failed: " + response.getStatusCode());
        }
    }

    /**
     *
     * @param refreshToken
     * @return
     */
    public CJAuthenticationResponse refreshToken(String refreshToken) {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);

        String requestBody = String.format("{\"refresh_token\": \"%s\"}", refreshToken);
        HttpEntity<String>  request = new HttpEntity<>(requestBody, headers);
        ResponseEntity<CJAuthenticationResponse>  response = restTemplate.postForEntity(
                config.getRefreshUrl(), request, CJAuthenticationResponse.class);
        if(response.getStatusCode() == HttpStatus.OK && response.getBody()!= null){
            return response.getBody();
        } else {
            throw new RuntimeException("Refresh token failed: " + response.getStatusCode());
        }

    }

}
