<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>litemall-all</artifactId>
    <packaging>jar</packaging>

    <parent>
        <groupId>org.linlinjava</groupId>
        <artifactId>litemall</artifactId>
        <version>0.1.0</version>
    </parent>



    <dependencies>
        <dependency>
            <groupId>org.linlinjava</groupId>
            <artifactId>litemall-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.linlinjava</groupId>
            <artifactId>litemall-db</artifactId>
        </dependency>

        <dependency>
            <groupId>org.linlinjava</groupId>
            <artifactId>litemall-wx-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.linlinjava</groupId>
            <artifactId>litemall-admin-api</artifactId>
        </dependency>

        <!-- For development purpose: use this command  -->
        <!-- mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005"-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>repackage</id>
                        <configuration>
                            <executable>true</executable>
                            <classifier>exec</classifier>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- maven-resource plugin -->
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-resources</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${basedir}/target/classes/static</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>../litemall-admin/dist</directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-resources-vue</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${basedir}/target/classes/static/vue</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>../litemall-vue/dist</directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-resources-all-react</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${basedir}/target/classes/static/react</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>../litemall-all-react-war/dist</directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>

                </executions>
            </plugin>

            <!-- Eirslett  plugin -->
            <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>${frontend-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>install-node-and-npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <configuration>
                            <nodeVersion>${node.version}</nodeVersion>
                            <npmVersion>${npm.version}</npmVersion>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm install</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                    </execution>
                    <!--<execution>
                        <id>webapp build test</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <phase>test</phase>
                        <configuration>
                            <arguments>run webapp:test</arguments>
                            <npmInheritsProxyConfigFromMaven>false</npmInheritsProxyConfigFromMaven>
                        </configuration>
                    </execution>
                    <execution>
                        <id>webapp build prod</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <phase>generate-resources</phase>
                        <configuration>
                            <arguments>run webapp:dev</arguments>
                            <environmentVariables>
                                <APP_VERSION>${project.version}</APP_VERSION>
                            </environmentVariables>
                            <npmInheritsProxyConfigFromMaven>false</npmInheritsProxyConfigFromMaven>
                        </configuration>
                    </execution>-->
                </executions>
            </plugin>

            <!-- Add Jib plugin for Docker image creation -->
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>${jib-maven-plugin.version}</version>
                <configuration>
                    <from>
                        <image>eclipse-temurin:17-jre</image>
                       <!-- <auth>
                            <username>${env.DOCKERHUB_USERNAME}</username>
                            <password>${env.DOCKERHUB_PASSWORD}</password>
                        </auth>-->
                    </from>
                    <to>
                        <image>${docker.image.prefix}/${project.artifactId}:${project.version}</image>
                    </to>
                    <container>
                        <ports>
                            <port>8082</port> <!-- Default Spring Boot port -->
                        </ports>
                        <jvmFlags>
                            <jvmFlag>-Dspring.profiles.active=prod</jvmFlag>
                        </jvmFlags>
                    </container>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <!-- Add a profile for building Docker images -->
        <profile>
            <id>docker</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.google.cloud.tools</groupId>
                        <artifactId>jib-maven-plugin</artifactId>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>