spring:
  profiles:
    active: db, core, elastic, admin, wx
  config:
    import: optional:classpath:application-db.yml
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: jdbc:mysql://localhost:3306/litemall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Calliste_1006
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath*:org/linlinjava/litemall/db/dao/*.xml
  type-aliases-package: org.linlinjava.litemall.db.domain
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8089
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org:
      linlinjava:
        litemall:
          db: DEBUG
  config: classpath:logback-spring.xml

swagger:
  production: false