<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.linlinjava</groupId>
		<artifactId>litemall</artifactId>
		<version>0.1.0</version>
	</parent>

	<artifactId>litemall-config</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>
	<description>Demo project for Spring Boot</description>


	<properties>
		<java.version>17</java.version>
		<mapstruct.version>1.5.2.Final</mapstruct.version>
		<jaxb-runtime.version>4.0.0</jaxb-runtime.version>
		<spring-cloud.version>2021.0.9</spring-cloud.version>

		<jib-maven-plugin.version>3.4.0</jib-maven-plugin.version>
		<jib-maven-plugin.image>eclipse-temurin:17-jre-focal</jib-maven-plugin.image>
		<jib-maven-plugin.architecture>amd64</jib-maven-plugin.architecture>


	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>${spring-boot.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-config-server</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-bootstrap</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-loadbalancer</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>


	<build>
		<plugins>
			<!-- spring boot build plugin -->
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<image>
						<builder>paketobuildpacks/builder-jammy-base:latest</builder>
					</image>
				</configuration>
			</plugin>

			<!-- jib docker build plugin -->
			<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>jib-maven-plugin</artifactId>
			</plugin>

		</plugins>


		<pluginManagement>
			<plugins>
				<!-- jib-maven plugin management -->
				<plugin>
					<groupId>com.google.cloud.tools</groupId>
					<artifactId>jib-maven-plugin</artifactId>
					<version>${jib-maven-plugin.version}</version>
					<configuration>
						<from>
							<image>${jib-maven-plugin.image}</image>
							<platforms>
								<platform>
									<architecture>${jib-maven-plugin.architecture}</architecture>
									<os>linux</os>
								</platform>
							</platforms>
						</from>
						<to>
							<image>announce-service:latest</image>
						</to>
						<container>
							<entrypoint>
								<shell>bash</shell>
								<option>-c</option>
								<arg>/entrypoint.sh</arg>
							</entrypoint>
							<ports>
								<port>8083</port>
								<port>5701/udp</port>
							</ports>
							<!--	<environment>
                                    <SPRING_OUTPUT_ANSI_ENABLED>ALWAYS</SPRING_OUTPUT_ANSI_ENABLED>
                                    <JHIPSTER_SLEEP>0</JHIPSTER_SLEEP>
                                </environment>-->
							<creationTime>USE_CURRENT_TIMESTAMP</creationTime>
							<user>1000</user>
						</container>
						<extraDirectories>
							<paths>src/main/docker/jib</paths>
							<permissions>
								<permission>
									<file>/entrypoint.sh</file>
									<mode>755</mode>
								</permission>
							</permissions>
						</extraDirectories>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>


</project>
